webtalk_init -webtalk_dir /homes/l18desuq/projets/CORDIC_FPGA/CORDIC_FPGA.sim/sim_1/behav/xsim/xsim.dir/cordic_iterative_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Feb  9 19:39:23 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210967703_174171490_210696477_328" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "7fa854d8-b12c-46a2-a611-f89a6beee627" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "9b5e061b906344399c5ce9da5dd9f539" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "19" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.4 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2349.581 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.02_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "125628_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2582878938 -regid "210967703_174171490_210696477_328" -xml /homes/l18desuq/projets/CORDIC_FPGA/CORDIC_FPGA.sim/sim_1/behav/xsim/xsim.dir/cordic_iterative_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /homes/l18desuq/projets/CORDIC_FPGA/CORDIC_FPGA.sim/sim_1/behav/xsim/xsim.dir/cordic_iterative_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /homes/l18desuq/projets/CORDIC_FPGA/CORDIC_FPGA.sim/sim_1/behav/xsim/xsim.dir/cordic_iterative_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
